name: "Turbo Changed"
description: "A Github Action making it easy to check if a local workspace changed using Turborepo."
author: "Trampoline"
branding:
  icon: git-branch
  color: green
inputs:
  turbo-command:
    required: true
    description: "The turbo command to run, e.g build. Also accepts arguments. e.g build --since=main"
  working-directory:
    required: false
    description: "Path to the root of the monorepo."
    default: "./"
outputs:
  changed:
    description: "True if the workspace changed, otherwise false."

runs:
  using: "node16"
  main: "dist/main.js"
